import os
import json

def test_winning_model_accuracy():
    metrics_path = "metrics.json"
    
    # Check if file exists
    assert os.path.exists(metrics_path), f"CI Failure: {metrics_path} was not generated by the pipeline."
    
    # Read metrics.json
    with open(metrics_path, "r") as f:
        metrics = json.load(f)
    
    winning_accuracy = metrics.get("accuracy", 0.0)
    model_name = metrics.get("model_type", "Unknown")
    
    print(f"--- Running CI Automated Test Verification ---")
    print(f"Validating model: {model_name}")
    print(f"Recorded Accuracy: {winning_accuracy:.4f}")
    
    # Continuous Integration Requirement: Assert winning accuracy >= 0.85
    assert winning_accuracy >= 0.85, f"CI Failure: Winning model accuracy ({winning_accuracy:.4f}) is below the required 0.85 threshold!"
    print("✅ CI Verification Passed: Winning model meets deployment standards.")

if __name__ == "__main__":
    test_winning_model_accuracy()
